---
# ©Copyright 2020 StackHPC Ltd.
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Install monasca-client into a Python virtualenv
  pip:
    name: python-monascaclient
    state: present
    version: 1.15.0
    virtualenv: "{{ monasca_client_virtualenv_dir }}"
  become: "{{ virtualenv_become }}"
  when: "'venv' not in skip_tasks"
  tags:
    - venv

- name: Setup default notification method
  vars:
    ansible_python_interpreter: "{{ monasca_client_virtualenv_dir }}/bin/python"
  monasca_notification_method:
    name: "{{ notification_name }}"
    type: "{{ notification_type }}"
    address: "{{ notification_address }}"
    keystone_url: "{{ keystone_url | default(omit) }}"
    keystone_user: "{{ keystone_user | default(omit) }}"
    keystone_password: "{{ keystone_password | default(omit) }}"
    keystone_project: "{{ keystone_project | default(omit) }}"
    keystone_token: "{{ keystone_token | default(omit) }}"
    monasca_api_url: "{{ monasca_api_url | default(omit) }}"
    monasca_endpoint_region: "{{ monasca_endpoint_region | default(omit) }}"
    monasca_endpoint_interface: "{{ monasca_endpoint_interface | default(omit) }}"
    state: "{{ state | default(omit) }}"
  when: "'notification' not in skip_tasks"
  tags:
    - always
  register: default_notification

# Include the various alarm sets
- include_tasks: alarms.yml
  vars:
    alarm_group: "System"
    alarm_definitions: "{{ system_alarm_definitions }}"
  when: "'system' not in skip_tasks"
  tags: system_alarms

- include_tasks: alarms.yml
  vars:
    alarm_group: "Monasca"
    alarm_definitions: "{{ monasca_alarm_definitions }}"
  when: "'monasca' not in skip_tasks"
  tags: monasca_alarms

- include_tasks: alarms.yml
  vars:
    alarm_group: "OpenStack"
    alarm_definitions: "{{ openstack_alarm_definitions }}"
  when: "'openstack' not in skip_tasks"
  tags: openstack_alarms

- include_tasks: alarms.yml
  vars:
    alarm_group: "Misc"
    alarm_definitions: "{{ misc_alarm_definitions }}"
  when: "'misc' not in skip_tasks"
  tags: service_alarms

- include_tasks: alarms.yml
  vars:
    alarm_group: "Ceph"
    alarm_definitions: "{{ ceph_alarm_definitions }}"
  when: "'ceph' not in skip_tasks"
  tags: ceph_alarms

- include_tasks: alarms.yml
  vars:
    alarm_group: "prometheus-haproxy-exporter"
    alarm_definitions: "{{ prometheus_haproxy_alarm_definitions }}"
  when: "'prometheus-haproxy' not in skip_tasks"
  tags: prometheus_haproxy

- include_tasks: alarms.yml
  vars:
    alarm_group: "prometheus-mysqld-exporter"
    alarm_definitions: "{{ prometheus_mysqld_alarm_definitions }}"
  when: "'prometheus-mysqld' not in skip_tasks"
  tags: prometheus_mysqld

- include_tasks: alarms.yml
  vars:
    alarm_group: "prometheus-openstack-exporter"
    alarm_definitions: "{{ prometheus_openstack_alarm_definitions }}"
  when: "'prometheus-openstack' not in skip_tasks"
  tags: prometheus_openstack

- include_tasks: alarms.yml
  vars:
    alarm_group: "Custom"
    alarm_definitions: "{{ custom_alarms }}"
  when: "'custom' not in skip_tasks"
  tags: custom_alarms
