---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Create Monasca Alarm Definitions
  vars:
    ansible_python_interpreter: "{{ monasca_client_virtualenv_dir }}/bin/python"
  monasca_alarm_definition:
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    expression: "{{ item.expression }}"
    match_by: "{{ item.match_by | default(['hostname']) }}"
    keystone_url: "{{ keystone_url | default(omit) }}"
    keystone_user: "{{ keystone_user | default(omit) }}"
    keystone_password: "{{ keystone_password | default(omit) }}"
    keystone_project: "{{ keystone_project | default(omit) }}"
    keystone_token: "{{ keystone_token | default(omit) }}"
    monasca_api_url: "{{ monasca_api_url | default(omit) }}"
    severity: "{{ item.severity | default('LOW') }}"
    state: "{{ state | default(omit) }}"
    alarm_actions:
      - "{{ default_notification.notification_method_id | default(omit) }}"
    ok_actions:
      - "{{ default_notification.notification_method_id | default(omit) }}"
    undetermined_actions:
      - "{{ default_notification.notification_method_id | default(omit) }}"
  with_items:
    - { name: "Kafka Consumer Lag",
        description: "Alarms when the specified consumer_group is not keeping up with the incoming messages",
        severity: "MEDIUM",
        expression: "avg(kafka.consumer_lag) > 1000 times 3",
        match_by: ["consumer_group", "hostname"] }
    - { name: "Monasca Agent Emit Time",
        description: "Alarms when the elapsed time that Monasca Agent takes to send metrics to Monasca API is high",
        expression: "avg(monasca.emit_time_sec) > 2 times 3" }
    - { name: "Monasca Agent Collection Time",
        description: "Alarms when the elapsed time the Monasca Agent takes to collect metrics is high",
        expression: "avg(monasca.collection_time_sec) > 5 times 3" }
    - { name: "ZooKeeper Latency",
        description: "Alarms when the ZooKeeper latency is high",
        expression: "avg(zookeeper.avg_latency_sec) > 1 times 3" }
