---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Create System Alarm Definitions
  vars:
    ansible_python_interpreter: "{{ monasca_client_virtualenv_dir }}/bin/python"
  monasca_alarm_definition:
    name: "{{ item.name }}"
    description: "{{ item.description | default('') }}"
    expression: "{{ item.expression }}"
    match_by: "{{ item.match_by | default(['hostname']) }}"
    keystone_url: "{{ keystone_url | default(omit) }}"
    keystone_user: "{{ keystone_user | default(omit) }}"
    keystone_password: "{{ keystone_password | default(omit) }}"
    keystone_project: "{{ keystone_project | default(omit) }}"
    keystone_token: "{{ keystone_token | default(omit) }}"
    monasca_api_url: "{{ monasca_api_url | default(omit) }}"
    monasca_endpoint_region: "{{ monasca_endpoint_region | default(omit) }}"
    monasca_endpoint_interface: "{{ monasca_endpoint_interface | default(omit) }}"
    severity: "{{ item.severity | default('LOW') }}"
    state: "{{ state | default(omit) }}"
    alarm_actions:
      - "{{ default_notification.notification_method_id | default(omit) }}"
    ok_actions:
      - "{{ default_notification.notification_method_id | default(omit) }}"
    undetermined_actions:
      - "{{ default_notification.notification_method_id | default(omit) }}"
  with_items:
    - { name: "Host Status",
        description: "Alarms when the specified host is down or not reachable",
        severity: "HIGH",
        expression: "host_alive_status > 0" }
    - { name: "CPU Usage",
        description: "Alarms when CPU usage is high",
        severity: "MEDIUM",
        expression: "avg(cpu.idle_perc) < 10 times 3" }
    - { name: "Disk Inode Usage",
        description: "Alarms when disk inode usage is high",
        severity: "MEDIUM",
        expression: "disk.inode_used_perc > 90",
        match_by: ["hostname", "device"] }
    - { name: "Disk Usage",
        description: "Alarms when disk usage is high",
        severity: "MEDIUM",
        expression: "disk.space_used_perc > 90",
        match_by: ["hostname", "device"] }
    - { name: "Memory Usage",
        description: "Alarms when memory usage is high",
        severity: "MEDIUM",
        expression: "avg(mem.usable_perc) < 10 times 3" }
    - { name: "Network Errors",
        description: "Alarms when either incoming or outgoing network errors are high",
        severity: "MEDIUM",
        expression: "net.in_errors_sec > 5 or net.out_errors_sec > 5" }
